name: PR Updated

on:
  pull_request:
    types: [synchronize]
    branches: [master]

jobs:
  send-pr-updated-notification:
    uses: domengabrovsek/github-actions/.github/workflows/pr-updated.yml@master
    with:
      api_url: ${{ vars.TELEGRAM_API_URL }}
      chat_id: ${{ vars.TELEGRAM_CHAT_ID }}